---
- name: Setup webserver and deploy app on n3
  hosts: n3
  become: yes
  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Install httpd
      yum:
        name: httpd
        state: present
    
    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Clone ecomm-3 repo into /var/www/html
      git:
        repo: "https://github.com/CeeyIT-Solutions/ecomm-3.git"
        dest: /var/www/html
