---
- name: Setup webserver and deploy app on n3
  hosts: n3
  become: yes
  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Install httpd
      yum:
        name: httpd
        state: present
    
    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy the static.html to /var/www/html/static.html
      copy:
        src: static.html
        dest: /var/www/html/static.html

...