---
- name: Setup webserver and deploy app on n-ubuntu
  hosts: n-ubuntu
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
