---
    - name: Install apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Start and enable apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "Centos"

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon" or ansible_distribution == "Centos"
... 
